# docker-compose.yml

services:
  bridgestrap:
    restart: unless-stopped
    profiles:
      - ENABLE_SERVER
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-bridgestrap
    #image: ghcr.io/gameplayer-8/bridgestrap
    tmpfs:
      - /var/log
      - /tmp
    healthcheck:
      test: "curl -sL http://127.0.0.1:5000 -o /dev/null"
      interval: 5s
      retries: 20
    networks:
      - tor
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '2'
          memory: 512M

  rdsys:
    restart: unless-stopped
    profiles:
      - ENABLE_SERVER
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-rdsys
    #image: ghcr.io/gameplayer-8/rdsys
    tmpfs:
      - /var/log
      - /tmp
    volumes:
      - moat:/opt/rdsys/storage
    depends_on:
      bridgestrap:
        condition: service_healthy
    healthcheck:
      test: "curl -sL http://127.0.0.1:8000/moat -o /dev/null"
      interval: 5s
      retries: 20
    networks:
      tor:
        ipv4_address: 172.16.51.50
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1G

  tor:
    restart: unless-stopped
    init: ${ENABLE_SPREAD:-true}
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-tor
    #image: ghcr.io/gameplayer-8/tor
    tmpfs:
      - /var/log
      - /tmp
#    depends_on:
#      rdsys:
#        condition: service_healthy
    healthcheck:
      test: "curl -sL --socks5 127.0.0.1:9050 https://check.torproject.org/ -o /dev/null"
      interval: 10s
      retries: 30
    networks:
      - tor
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '1'
          memory: 512M

  load_balancer_socks:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-haproxy-socks
    #image: ghcr.io/gameplayer-8/haproxy-socks
    ports:
      - "9050:9050/tcp"
    depends_on:
      tor:
        condition: service_healthy
    healthcheck:
      test: "nc -z 127.0.0.1 9050"
      interval: 5s
      retries: 20
    networks:
      - tor
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  load_balancer_trans:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-haproxy-trans
    #image: ghcr.io/gameplayer-8/haproxy-trans
    ports:
      - "9040:9040/tcp"
    depends_on:
      tor:
        condition: service_healthy
    healthcheck:
      test: "nc -z 127.0.0.1 9040"
      interval: 5s
      retries: 20
    networks:
      - tor
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

#  udp_tunnel_socks:
#    build:
#      context: .
#      dockerfile: dockerfiles/Dockerfile-udp2raw
#    #image: ghcr.io/gameplayer-8/udp2raw
#    command: >
#      -s -l0.0.0.0:9050 -r load_balancer_socks:9050
#    ports:
#      - "9050:9050/udp"
#    depends_on:
#      load_balancer_socks:
#        condition: service_healthy
#    networks:
#      - tor

volumes:
  moat:
    name: moat

networks:
  tor:
    name: tor
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.51.0/24
        - subnet: fd4d:6169:6b33:5f72::/64
